### ISSUE TITLE
ImportError: No module named 'uclassify_eh'

### ISSUE THREAD

**Issue by mattiasostmar** [psibi/pyuClassify#4] opened 2015-03-13 14:23 UTC
Why do I get this? The file classify_eh.py is located in the same folder as classify.py.

---

ImportError                               Traceback (most recent call last)
<ipython-input-36-3a9f49efcf7c> in <module>()
      2 from textblob import TextBlob
      3 import re
----> 4 from uclassify import uclassify

//anaconda/lib/python3.4/site-packages/uclassify/**init**.py in <module>()
----> 1 from uclassify import uclassify

//anaconda/lib/python3.4/site-packages/uclassify/uclassify.py in <module>()
     26 from xml.dom.minidom import Document
     27 from time import gmtime, strftime
---> 28 from uclassify_eh import uClassifyError
     29 import xml.dom.minidom
     30 import requests

ImportError: No module named 'uclassify_eh'

**Comment by psibi** [comment] 2015-03-13 15:55
@mattiasostmar How did you install uclassify ? If it's a Linux system, install it like this: `sudo pip install uclassify`

**Comment by mattiasostmar** [comment] 2015-03-15 19:50
I'm on mac os x (Yosemite 10.10.2) and installed uclassify with `pip install uclassify`
I use a python distribution named [Anaconda] (https://store.continuum.io/cshop/anaconda/), but from what I've understood it should not create troubles even though I also install libraries using `pip install` instead of the libraries one can install from Anaconda using `conda install`.

**Comment by mattiasostmar** [comment] 2015-03-16 21:01
I also tried installing pyuClassify by cloning the git repo (pip uninstall first), but with the same error message.

**Comment by psibi** [comment] 2015-03-16 21:10
@mattiasostmar When does the error come ? Can you give a minimal example of the program which reproduces this behavior?

**Comment by mattiasostmar** [comment] 2015-03-16 21:16
If fails directly on import, wether I run it in a script-file (a) or in iPython interactive interpreter (b)

a) mosmbp:~ mos$ python utest.py
Traceback (most recent call last):
  File "utest.py", line 1, in <module>
    import uclassify
  File "//anaconda/lib/python3.4/site-packages/uclassify-0.1.2-py3.4.egg/uclassify/__init__.py", line 1, in <module>
  File "//anaconda/lib/python3.4/site-packages/uclassify-0.1.2-py3.4.egg/uclassify/uclassify.py", line 28, in <module>
ImportError: No module named 'uclassify_eh'

b) 
In [1]: import uclassify
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-15826f7da8ed> in <module>()
----> 1 import uclassify

/Users/mos/pyuClassify/uclassify/__init__.py in <module>()
----> 1 from uclassify import uclassify

/Users/mos/pyuClassify/uclassify/uclassify.py in <module>()
     26 from xml.dom.minidom import Document
     27 from time import gmtime, strftime
---> 28 from uclassify_eh import uClassifyError
     29 import xml.dom.minidom
     30 import requests

ImportError: No module named 'uclassify_eh'

**Comment by psibi** [comment] 2015-03-16 21:18
@mattiasostmar  What does your file `utest.py` contain ?

**Comment by mattiasostmar** [comment] 2015-03-17 10:35
Ah, only:
ìmport uclassify´
Sorry, for that. ;-)

**Comment by stuboo** [comment] 2017-04-02 13:00
I'm getting this same error.

```
Traceback (most recent call last):
  File "/Users/jrs/PycharmProjects/mesh_keywords/get-news.py", line 5, in <module>
    from uclassify import uclassify
  File "/Users/jrs/anaconda/lib/python3.5/site-packages/uclassify-0.1.2-py3.5.egg/uclassify/__init__.py", line 1, in <module>
  File "/Users/jrs/anaconda/lib/python3.5/site-packages/uclassify-0.1.2-py3.5.egg/uclassify/uclassify.py", line 28, in <module>
ImportError: No module named 'uclassify_eh'
```

get-news.py looks like this...
```
import requests
from readability import Document
from bs4 import BeautifulSoup
import json
from uclassify import uclassify

response = requests.get('http://myurl.net')
doc = Document(response.text)
soup = BeautifulSoup(doc.content(), "lxml")
text = soup.get_text()
print(text)

a = uclassify()
a.setWriteApiKey('MY_WRITE_KEY')
a.setReadApiKey('MY_READ_KEY')
d = a.classify(text,"Sentiment")
print(d)
```

I installed to an anaconda 3.5.1 installation by cloning the git repo
```
$ git clone git://github.com/psibi/pyuClassify.git
$ cd uclassify
$ sudo python setup.py install
```

`uclassify_eh.py` is in the same directory as `uclassify.py`

Thanks for the help.  Looking forward to using this module.

**Comment by psibi** [comment] 2017-04-02 13:05
@stuboo Which python version are you using ?

**Comment by psibi** [comment] 2017-04-02 13:06
Oh, I think it's Python 3.5. I actually have tested this only on Python 2.* series. I will be willing to accept a PR for supporting Python 3.

**Comment by stuboo** [comment] 2017-04-02 14:02
It is Python 3.5.

> I will be willing to accept a PR for supporting Python 3.

No idea what this means or how to do it.  I suppose I'll just keep following the repo until it is updated for version 3. Thanks.

**Comment by psibi** [comment] 2017-04-02 15:01
@stuboo I have fixed the issues. Can you try it freshly and let me know ? If it works for you, I will publish a new version.

**Comment by stuboo** [comment] 2017-04-02 15:21
That was fast.  Thank you.

```
Traceback (most recent call last):
  File "/Users/jrs/PycharmProjects/mesh_keywords/get-news.py", line 35, in <module>
    d = a.classify(text,"Sentiment")
  File "/Users/jrs/anaconda/lib/python3.5/site-packages/uclassify-0.1.2-py3.5.egg/uclassify/uclassify.py", line 263, in classify
uclassify.uclassify_eh.uClassifyError: "Authentification with the api key 'xxxxxxxxxMKx' for the classifier 'Sentiment' failed. The classifier doesn't exist."
```

**Comment by psibi** [comment] 2017-04-02 15:33
@stuboo The error message is saying that you haven't created the classifier yet.

You have to create it using something like this: `a.create("classifierName")`. You can see the README to find more details on how to use the library: https://github.com/psibi/pyuClassify#usage

**Comment by stuboo** [comment] 2017-04-02 16:02
Thank you.  Works perfectly.  I was trying to use a preexisting classifier, so I just added the username of the creator and it worked like a charm.

`d = a.classify(text,'sentiment','uclassify')`

I appreciate your help and your work on this module.  Many thanks.

**Comment by psibi** [comment] 2017-04-02 16:51
Awesome. I have released a new version. Closing this issue.

**Closed by psibi** 2017-04-02 16:51 UTC

**Comment by Sorooshi** [comment] 2019-04-16 14:57
@psibi I am following your instruction as you mentioned in [here](https://github.com/psibi/pyuClassify#usage)

But I can't call it through Jupyternote Book nor in any .py file. 

from uclassify import uclassify 

Here is the error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-b80526abc695> in <module>()
----> 1 from uclassify import uclassify

ModuleNotFoundError: No module named 'uclassify'


My operating system is Ubuntu 18.04.

**Comment by psibi** [comment] 2019-04-18 16:23
@Sorooshi Does this work for you outside of Jupyternote book in the Python interpreter ?

**Comment by Sorooshi** [comment] 2019-04-18 21:47
@psibi Yes it works outside of Jupyternote book.

**Comment by psibi** [comment] 2019-04-19 06:23
@Sorooshi Ah, I see. I would be happy to accept a PR for this fixing it for Jupyterbook.
